name: Test Deployment Workflow Github Actions
on:
  push:
    branches: [ master ]

jobs: 
  job_one:
    name: My Testing Deployement
    runs-on: ubuntu-latest
    steps:
    - name: Testing Auto Deployment Go to VPS inside Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HAMASA_HOST }}
        username: ${{ secrets.HAMASA_USERNAME }}
        key: ${{ secrets.SECRET_KEY }}
        port: 22
        script: |
          cd ${{ secrets.PATH }}
          git pull origin master
          git status
          git log